/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.car;
import model.carFleet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
/**
 *
 * @author sirip
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    carFleet fleet;
    public CreateJPanel(carFleet fleet) {
        initComponents();
        this.fleet = fleet;
        
    }
    String regexManfName = "^[a-zA-Z ]+$";
    String regexNumberField = "^[0-9]+$";
    String regexSerialNumber = "^[A-Z0-9]{5}$";
    String regexModelNumber = "^[a-zA-Z0-9]{1,8}$";
    String regexCity = "^[a-zA-Z ]+$";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        lblAvailability = new javax.swing.JLabel();
        checkboxAvailability = new javax.swing.JCheckBox();
        lblManufacturer = new javax.swing.JLabel();
        txtManufacturer = new javax.swing.JTextField();
        lblManfyear = new javax.swing.JLabel();
        txtManfyear = new javax.swing.JTextField();
        lblNseats = new javax.swing.JLabel();
        txtNseats = new javax.swing.JTextField();
        lblSerialno = new javax.swing.JLabel();
        txtSerialno = new javax.swing.JTextField();
        lblModelno = new javax.swing.JLabel();
        txtModelno = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        lblExpired = new javax.swing.JLabel();
        checkboxExpired = new javax.swing.JCheckBox();
        txtEta = new javax.swing.JTextField();
        lblEta = new javax.swing.JLabel();

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create Car Fleet");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblAvailability.setText("Availability:");

        lblManufacturer.setText("Manufacturer:");

        lblManfyear.setText("Manufactured Year:");

        lblNseats.setText("Number of Seats:");

        lblSerialno.setText("Serial Number:");

        lblModelno.setText("Model Number:");

        lblCity.setText("City:");

        lblExpired.setText("Expired Maintenance Certificate:");

        lblEta.setText("ETA:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblManfyear)
                                    .addComponent(lblNseats)
                                    .addComponent(lblSerialno)
                                    .addComponent(lblModelno)
                                    .addComponent(lblCity)
                                    .addComponent(lblExpired)
                                    .addComponent(lblEta))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtCity, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                        .addComponent(txtModelno)
                                        .addComponent(txtSerialno)
                                        .addComponent(txtNseats)
                                        .addComponent(txtManfyear, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(checkboxExpired)
                                    .addComponent(txtEta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAvailability)
                                    .addComponent(lblManufacturer))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkboxAvailability)
                                    .addComponent(txtManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(btnSave)))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblTitle)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManufacturer)
                    .addComponent(txtManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(checkboxAvailability, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManfyear)
                    .addComponent(txtManfyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNseats)
                    .addComponent(txtNseats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSerialno)
                    .addComponent(txtSerialno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModelno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModelno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCity))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblExpired, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkboxExpired))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEta)
                    .addComponent(txtEta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btnSave)
                .addContainerGap(128, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public boolean regexEvaluator(String input, String regexPattern, String whichPattern){
        if (input.matches(regexPattern) == true) {
            return true;
        }
        else {
            String errorMSG = String.format("Please enter valid %s", whichPattern);
            JOptionPane.showMessageDialog(this, errorMSG);
            return false;
        }
    }
    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        car c = new car();
        String manufacturer = txtManufacturer.getText();
        String serialno = txtSerialno.getText();
        String modelno = txtModelno.getText();
        String city = txtCity.getText();
        
        
        boolean checkSerialUnique = true;
        boolean checkYearValid = true;
        
        boolean checkManfName = regexEvaluator(manufacturer, regexManfName, "Manufacturer Name");       
        boolean checkSerialNumber = regexEvaluator(serialno, regexSerialNumber, "Serial Number [5 chars Uppercase Aplhanumeric]");
        boolean checkModelNumber = regexEvaluator(modelno, regexModelNumber, "Model Number");
        boolean checkCity = regexEvaluator(city, regexCity, "City");
        
        
        try {
            int manfyear = Integer.parseInt(txtManfyear.getText());
            c.setManfyear(manfyear);
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "Manucaturing year must be an integer."); 
        }
        try {
            int nseats = Integer.parseInt(txtNseats.getText());
            c.setNseats(nseats);
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "Number of seats must be an integer."); 
        }  
        try {
            int eta = Integer.parseInt(txtEta.getText());
            c.setEta(eta);
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "ETA minutes must be an integer."); 
        }        
        
        for (car cr: fleet.getFleet()){
            if (cr.getSerialno().equals(serialno)){
                checkSerialUnique = false;
                JOptionPane.showMessageDialog(this, "Please enter a unique serial number."); 
            } 
        }
        if (c.getManfyear()>=2021 || c.getManfyear()<=1980){
            checkYearValid = false;
            JOptionPane.showMessageDialog(this, "Please enter a valid Year of Manufacturing (>1980 and <2021).");
        }

        
        if (checkManfName && checkSerialNumber && checkModelNumber &&
                checkCity && checkSerialUnique && checkYearValid) {                  

            c.setManufacturer(manufacturer);
            c.setAvailability(checkboxAvailability.isSelected());
            c.setSerialno(serialno);
            c.setModelno(modelno);
            c.setCity(city);
            c.setExpired(checkboxExpired.isSelected());
            
            fleet.addNewCar(c);
            

            JOptionPane.showMessageDialog(this, "New Car Added to the fleet.");
            
            txtManufacturer.setText("");
            checkboxAvailability.setSelected(false);  
            txtManfyear.setText("");
            txtNseats.setText("");
            txtSerialno.setText("");
            txtModelno.setText("");
            txtCity.setText("");
            checkboxExpired.setSelected(false);
            txtEta.setText("");    
            
        }

        
  
        
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox checkboxAvailability;
    private javax.swing.JCheckBox checkboxExpired;
    private javax.swing.JLabel lblAvailability;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblEta;
    private javax.swing.JLabel lblExpired;
    private javax.swing.JLabel lblManfyear;
    private javax.swing.JLabel lblManufacturer;
    private javax.swing.JLabel lblModelno;
    private javax.swing.JLabel lblNseats;
    private javax.swing.JLabel lblSerialno;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtEta;
    private javax.swing.JTextField txtManfyear;
    private javax.swing.JTextField txtManufacturer;
    private javax.swing.JTextField txtModelno;
    private javax.swing.JTextField txtNseats;
    private javax.swing.JTextField txtSerialno;
    // End of variables declaration//GEN-END:variables
}
