/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import model.car;
import model.carFleet;
import java.util.stream.Collectors;

/**
 *
 * @author sirip
 */
public class FilterJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FilterJPanel
     */
    carFleet fleet;
    public FilterJPanel(carFleet fleet) {
        initComponents();
        
        this.fleet = fleet;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblFleet = new javax.swing.JTable();
        lblFilterTitle = new javax.swing.JLabel();
        btnNumAvailable = new javax.swing.JButton();
        btnFirstAvailable = new javax.swing.JButton();
        txtNumUnavailable = new javax.swing.JTextField();
        lblHeadAvail = new javax.swing.JLabel();
        lblHeadUnavailable = new javax.swing.JLabel();
        txtNumAvailable = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1201, 567));

        tblFleet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Manufacturer", "Availability", "Manufactured Year", "Number of Seats", "Serial Number", "Model Number", "City", "Expired Lic. Certificate", "ETA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFleet.setShowGrid(false);
        tblFleet.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblFleet);

        lblFilterTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFilterTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFilterTitle.setText("Filtered Car Fleet");

        btnNumAvailable.setText("Number of Cars");
        btnNumAvailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumAvailableActionPerformed(evt);
            }
        });

        btnFirstAvailable.setText("First Available Car");
        btnFirstAvailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstAvailableActionPerformed(evt);
            }
        });

        lblHeadAvail.setText("Available");

        lblHeadUnavailable.setText("Unavailable");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFilterTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 1201, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFirstAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNumAvailable)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNumAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblHeadAvail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtNumUnavailable, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblHeadUnavailable))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblFilterTitle)
                .addGap(46, 46, 46)
                .addComponent(btnFirstAvailable)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHeadAvail)
                    .addComponent(lblHeadUnavailable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNumAvailable)
                    .addComponent(txtNumUnavailable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnFirstAvailableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstAvailableActionPerformed
        // TODO add your handling code here:
        
        ArrayList tempFleet = new ArrayList<car>();

        tempFleet.clear();
        
        for (car c:fleet.getFleet()){
            tempFleet.add(c);
        }
        Collections.sort(tempFleet);
        populateSelectedTable(tempFleet, 1);
    }//GEN-LAST:event_btnFirstAvailableActionPerformed

    private void btnNumAvailableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumAvailableActionPerformed
        // TODO add your handling code here:
        ArrayList tempFleetAvail = new ArrayList<car>();
        ArrayList tempFleetUnavail = new ArrayList<car>();
        
        int numAvail = 0;
        int numUnavail = 0;
        for (car c:fleet.getFleet()){
            if (c.isAvailability()){
                tempFleetAvail.add(c);
            }
            else{
                tempFleetUnavail.add(c);
            }
        }
        txtNumAvailable.setText(String.valueOf(tempFleetAvail.size()));
        txtNumUnavailable.setText(String.valueOf(tempFleetUnavail.size()));
        
    }//GEN-LAST:event_btnNumAvailableActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFirstAvailable;
    private javax.swing.JButton btnNumAvailable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFilterTitle;
    private javax.swing.JLabel lblHeadAvail;
    private javax.swing.JLabel lblHeadUnavailable;
    private javax.swing.JTable tblFleet;
    private javax.swing.JTextField txtNumAvailable;
    private javax.swing.JTextField txtNumUnavailable;
    // End of variables declaration//GEN-END:variables

    private void populateSelectedTable(ArrayList<car> selectedFleet, int limit) {
        
        DefaultTableModel model = (DefaultTableModel) tblFleet.getModel();
        model.setRowCount(0);
        int i = 0;  
        
        for (car c : selectedFleet){
            if (i >= limit){
                break;
            }            
            Object[] row = new Object[9];
            
            row[0] = c;
            row[1] = c.isAvailability();
            row[2] = c.getManfyear();
            row[3] = c.getNseats();
            row[4] = c.getSerialno();
            row[5] = c.getModelno();
            row[6] = c.getCity();
            row[7] = c.isExpired();
            row[8] = c.getEta();
            model.addRow(row);
            i++;
        }
    }
    
}
